#!perl -w
# Copyright (C) all contributors <meta@public-inbox.org>
# License: AGPL-3.0+ <https://www.gnu.org/licenses/agpl-3.0.txt>
use v5.12;
use Socket qw(pack_sockaddr_un);
use PublicInbox::Syscall ();
use PublicInbox::IPCSocket qw(lei_client_socket lei_sock_path);
my $narg = 5;
my ($sock, $sock_type);
my $recv_cmd = PublicInbox::Syscall->can('recv_cmd4') // do {
	# configure Inline::C + Spawn before loading PublicInbox::IPC
	my $inline_dir = $ENV{PERL_INLINE_DIRECTORY} //= (
			$ENV{XDG_CACHE_HOME} //
			( ($ENV{HOME} // '/nonexistent').'/.cache' )
			).'/public-inbox/inline-c';
	if (!-d $inline_dir) {
		require File::Path;
		File::Path::make_path($inline_dir);
	}
	require PublicInbox::Spawn; # takes ~50ms even if built *sigh*
	PublicInbox::Spawn->can('recv_cmd4');
} // die 'please install Inline::C for SCM_RIGHTS support';

my %pids;
my $sigchld = sub {
	my $flags = scalar(@_) ? POSIX::WNOHANG() : 0;
	for my $pid (keys %pids) {
		delete($pids{$pid}) if waitpid($pid, $flags) == $pid;
	}
};
my @parent;
my $exec_cmd = sub {
	my ($io, $argc, @argv) = @_;
	my $parent = $$;
	require POSIX;
	my @old = (\*STDIN, \*STDOUT, \*STDERR);
	my @rdr = map { (shift(@old), $_) } @$io;
	my $do_exec = sub {
		my @non_std; # ex. $op_p from lei_edit_search
		while (my ($io, $newfh) = splice(@rdr, 0, 2)) {
			my $old_io = !!$io;
			open $io, '+<&', $newfh or die "open +<&=: $!";
			push @non_std, $io unless $old_io;
		}
		if (@non_std) {
			require Fcntl;
			fcntl($_, Fcntl::F_SETFD(), 0) for @non_std;
		}
		my %env = map { split(/=/, $_, 2) } splice(@argv, $argc);
		@ENV{keys %env} = values %env;
		umask 077;
		exec(@argv);
		warn "exec: @argv: $!\n";
		POSIX::_exit(1);
	};
	$SIG{CHLD} = $sigchld;
	my $pid = fork // die "fork: $!";
	if ($pid == 0) {
		$do_exec->() if $io->[1]; # git-credential, pager

		# parent backgrounds on MUA
		POSIX::setsid() > 0 or die "setsid: $!";
		@parent = ($parent);
		return; # continue $recv_cmd in background
	}
	if ($io->[1]) {
		$pids{$pid} = undef;
	} else {
		$do_exec->(); # MUA reuses stdout
	}
};

my $runtime_dir = ($ENV{XDG_RUNTIME_DIR} // '') . '/lei';
if ($runtime_dir eq '/lei') {
	require File::Spec;
	$runtime_dir = File::Spec->tmpdir."/lei-$<";
}
unless (-d $runtime_dir) {
	require File::Path;
	File::Path::make_path($runtime_dir, { mode => 0700 });
}
($sock, $sock_type) = lei_client_socket();
my $path = lei_sock_path($runtime_dir, $narg, $sock_type);
my $addr = pack_sockaddr_un($path);
unless (connect($sock, $addr)) { # start the daemon if not started
	local $ENV{PERL5LIB} = join(':', @INC);
	open(my $daemon, '-|', $^X, $^W ? ('-w') : (),
		qw[-MPublicInbox::LEI -e PublicInbox::LEI::lazy_start(@ARGV)],
		$path, $! + 0, $narg, $sock_type) or die "popen: $!";
	while (<$daemon>) { warn $_ } # EOF when STDERR is redirected
	close($daemon) or warn <<"";
lei-daemon could not start, exited with \$?=$?

	# try connecting again anyways, unlink+bind may be racy
	connect($sock, $addr) or die <<"";
connect($path): $! (after attempted daemon start)

}
my @io = (\*STDIN, \*STDOUT, \*STDERR, undef);
open $io[3], '<', '.' or die "open(.) $!";
my $buf = join("\0", scalar(@ARGV), @ARGV);
while (my ($k, $v) = each %ENV) { $buf .= "\0$k=$v" }
$buf .= "\0\0";
require PublicInbox::IPC; # FIXME: slow loading
PublicInbox::IPC::sendcmd($sock, \@io, $buf) // die "sendmsg: $!";
$SIG{TSTP} = sub { PublicInbox::IPC::send_pkt($sock, 'STOP'); kill 'STOP', $$ };
$SIG{CONT} = sub { PublicInbox::IPC::send_pkt($sock, 'CONT') };

my $x_it_code = 0;
while (1) {
	@io = ();
	@io = PublicInbox::IPC::recvcmd($sock, $buf);
	die "recvmsg: $!" if scalar(@io) == 1 && !defined($io[0]);
	last if $buf eq '';
	if ($buf =~ /\Aexec (.+)\z/) {
		$exec_cmd->(\@io, split(/\0/, $1));
	} elsif ($buf eq '-WINCH') {
		kill($buf, @parent); # for MUA
	} elsif ($buf eq 'umask') {
		PublicInbox::IPC::send_pkt($sock, 'u'.pack('V', umask)) //
			die "send: $!"
	} elsif ($buf =~ /\Ax_it ([0-9]+)\z/) {
		$x_it_code ||= $1 + 0;
		last;
	} elsif ($buf =~ /\Achild_error ([0-9]+)\z/) {
		$x_it_code ||= $1 + 0;
	} elsif ($buf eq 'wait') {
		$sigchld->();
	} else {
		$sigchld->();
		die $buf;
	}
}
$sigchld->();
if (my $sig = ($x_it_code & 127)) {
	kill $sig, $$;
	select undef, undef, undef, 0; # for kernel to act on signal
}
exit($x_it_code >> 8);
